{% set name = "cyavro" %}
{% set version = "0.7.0" %}
{% set avro_version = "1.8.*" %}
{% set sha256 = "ffc62185db31410efb8e394f112f34d86aa3d2b987477ca1fcc079dc69715219" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
   fn: {{ name }}-{{ version }}.tar.gz
   url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
   sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win]
  script: python setup.py install

requirements:
    build:
        - python
        - cython
        - numpy x.x
        - toolchain
        - avro {{ avro_version }}
        - six
        - jinja2
    run:
        - python
        - numpy x.x
        - avro {{ avro_version }}
        - pandas >=0.16
        - filelock
        - six
        - python-avro

test:
    imports:
        - cyavro
    commands:
        - conda inspect linkages cyavro  # [linux]
        - conda inspect objects cyavro  # [osx]

about:
  home: https://github.com/maxpoint/cyavro
  license: BSD 3-clause
  license_family: BSD
  license_file: LICENSE
  summary: Fast avro reader / writer using libavro
  doc_url: https://maxpoint.github.io/cyavro

extra:
  recipe-maintainers:
    - mariusvniekerk
    - ericdill
