{% set name = "cyavro" %}
{% set version = "0.7.1" %}
{% set sha256 = "8a475905bb72a9ebb31bc0a41e9a72ca1db790ebf2935bed0e97f42a7704078b" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
   url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
   sha256: {{ sha256 }}

build:
  number: 1002
  skip: True  # [win]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
    build:
      - {{ compiler('c') }}
      - {{ compiler('cxx') }}  
    host:
      - python
      - pip
      - cython
      - numpy
      - avro
      - six
      - jinja2
    run:
      - python
      - pip
      - numpy
      - avro
      - pandas >=0.16
      - filelock
      - six
      - python-avro

test:
    imports:
      - cyavro

about:
  home: https://github.com/maxpoint/cyavro
  license: BSD 3-clause
  license_family: BSD
  license_file: LICENSE
  summary: Fast avro reader / writer using libavro
  doc_url: https://maxpoint.github.io/cyavro

extra:
  recipe-maintainers:
    - mariusvniekerk
    - parente
