appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: GckQSpcGc9EvO+JH1SdUHyxk+oul6KqWKzVVAxJKo4JUU+KQ8e2Wftvfpbt5P/na7Wj+bA5Eoa9aJc7PMw5FgQolWXzef2ejQ37pN2rwMPaH3ab93LRf9KsY84eZ2sBvx6hOLCm+6Txa0ns0O1CFg71wpJIx3dnjfHiWXNgl3nlBTNaaSMWYdihVcqpZ6ZfvheROruaK2n3GJzE0BbYt4Thk71+LriJcC5C5xKlDbsmBj2NRbPpKo+roCimtBh6SftuIouFMKTDSHU2dmah227ODu6w/Mb79ANFWAAZ6r9e8EM3fK93ICdnp6PmjeClSJrssdrLJmjskdHDCjALR53FkJRoLuZY0WLiyk8a3j40sv1UvBxQhZrZsjLG8tMr3I6R2GFsc9Ct3Qh7kvFZbqegTgX5uj8/Y5wfv+8inGJqorucCdMIKjNv/M1dmnSubl2RAq6X3sm/rV8a1UpglIfzP18zJj6xW4fjTFrelRWalU84l7b9qrUkp1NPbQz+ZeZY+qpmzQjcaf1ohdYa8LDMMfoJUbZ+8pMZ9alPqQxB1+puLvJcGCV1XL0HlUi5jIMcoJiaIr+TToSiLhQfAQKBg6E8dTfoxTb7VzZty+OW6kOjQ8UnyOhQeAlPuiDY8nhLuTq5/nz5KZmfRVO2CodA+ZQ5iZkEYtgBNuknrzDY=}
