travis:
  secure:
    BINSTAR_TOKEN: oEcrSgoUsKL34KQqODPgsA6htv0It3+UbTkWgwkY0J3RutrOYYST1xnCVqZtKZjAd2lcthYPhAnOPznJr9nl/yCm1J3Fps3kN9atvF0ogRJt7uxssnZzH02D1mmJfAVmS9/64oN3MWaSiPycJr9kPKt3pEEBzPx0ZtACEg7W6cSOF59db+8vNJh4ZydrejI4sY94gZwiwjsq2P4FTH0P64rCyYIDTk+bD+4MKsKH1x4mJd7toZVBeE+0WzisnTYZKJYYe1B0LXqjqzP036I/bBl8eWnLcL3MzrRppmEdyQ3nZzGtzXDdzz9D5AAzvCIskMWDCtHG3PUUNWwrF39PwX/deGdgwTaoTDs3WTgnknutAX9JTZzF/uwx0R9gJMe7GMP1T8g9sPamWv/du/eS616SbbK3wCuEzAqpVM1yZFocCqZoNS1UVg+DLXZzFT3ZJH0+r7bLb/N/0qscFBAZtKcbB/ywJaKZPNtoY+OR4S3U+BfZVreZWP2wkeW3+0cWBQIxOfAsnMYaJsOYPW7JtFGkqj32z8YUeX4953nA8nyfRv//JHJQfEaZ74GiWAGBCUV/qgBzLUKssCx539ZS2XIy5htLxLi/VaieY2ja1lDebo9DQSes36w8AaKuz6tN3NkQv4BtM6skmo+RQNOCgJQWzysQRv1pHUouphlixOg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
